const petDatabase = [
    {
        id: 1,
        name: "TOSHI",
        age: 1,
        weight: 12,
        gender: "Female",
        personality: "Gentle & playful",
        image: "images/dog11.png",
        description: "Toshi is spayed and overflowing with affection—always ready to greet you with a wagging tail and eyes full of love. With her gentle eyes and playful spirit, she's ready to bring warmth and joy into your life.",
        breed: "Golden Retriever Mix",
        vaccinated: true,
        neutered: true,
        goodWith: ["Children", "Other dogs", "Cats"],
        activityLevel: "Medium"
    },
    {
        id: 2,
        name: "SADIE",
        age: 2,
        weight: 18,
        gender: "Female",
        personality: "Friendly & Energetic",
        image: "images/dog12.png",
        description: "Sadie is a bundle of energy and enthusiasm! She loves running, playing fetch, and going on adventures. Her friendly nature makes her a perfect companion for an active family. She's house-trained and knows basic commands.",
        breed: "Border Collie Mix",
        vaccinated: true,
        neutered: true,
        goodWith: ["Active families", "Other dogs"],
        activityLevel: "High"
    },
    {
        id: 3,
        name: "GIZMO",
        age: 4,
        weight: 5,
        gender: "Male",
        personality: "Loving & curious",
        image: "images/dog10.png",
        description: "Gizmo may be small, but his heart is enormous! This curious little fellow loves to explore and will keep you entertained with his antics. He's a perfect lap dog who also enjoys short walks and meeting new people.",
        breed: "Yorkshire Terrier",
        vaccinated: true,
        neutered: true,
        goodWith: ["Seniors", "Apartment living", "Children"],
        activityLevel: "Low to Medium"
    },
    {
        id: 4,
        name: "BELLA",
        age: 3,
        weight: 30,
        gender: "Female",
        personality: "Calm & affectionate",
        image: "images/dog9.png",
        description: "Bella is the definition of a gentle giant. She's calm, affectionate, and loves nothing more than lounging by your side. She's great with children and other pets, making her perfect for families. Her favorite activities include long walks and belly rubs.",
        breed: "Labrador Mix",
        vaccinated: true,
        neutered: true,
        goodWith: ["Children", "Other pets", "Families"],
        activityLevel: "Medium"
    },
    {
        id: 5,
        name: "MAX",
        age: 2,
        weight: 20,
        gender: "Male",
        personality: "Energetic & Loyal",
        image: "images/dog11.png",
        description: "Max is a loyal companion who forms strong bonds with his humans. He's energetic and playful, always up for a game of fetch or a run in the park. Max is intelligent and eager to please, making him easy to train.",
        breed: "Australian Shepherd Mix",
        vaccinated: true,
        neutered: true,
        goodWith: ["Active owners", "Families", "Other dogs"],
        activityLevel: "High"
    },
    {
        id: 6,
        name: "LUNA",
        age: 1,
        weight: 8,
        gender: "Female",
        personality: "Playful & Sweet",
        image: "images/dog12.png",
        description: "Luna is a sweet young pup who loves to play and cuddle in equal measure. She's still learning about the world but approaches everything with enthusiasm and joy. Luna is partially house-trained and eager to learn more.",
        breed: "Beagle Mix",
        vaccinated: true,
        neutered: true,
        goodWith: ["First-time owners", "Families", "Other pets"],
        activityLevel: "Medium"
    },
    {
        id: 7,
        name: "ROCKY",
        age: 5,
        weight: 25,
        gender: "Male",
        personality: "Strong & Protective",
        image: "images/dog11.png",
        description: "Rocky is a distinguished gentleman who takes his role as protector seriously. He's loyal, smart, and will stand by your side through thick and thin. While reserved at first, he warms up quickly to his trusted humans.",
        breed: "German Shepherd Mix",
        vaccinated: true,
        neutered: true,
        goodWith: ["Experienced owners", "Families with older children"],
        activityLevel: "Medium to High"
    },
    {
        id: 8,
        name: "DAISY",
        age: 2,
        weight: 15,
        gender: "Female",
        personality: "Gentle & Loving",
        image: "images/dog12.png",
        description: "Daisy is a gentle soul who approaches life with a wagging tail and an open heart. She loves cuddles, short walks, and making new friends. Her sweet disposition makes her perfect for families or first-time pet owners.",
        breed: "Cavalier King Charles Spaniel Mix",
        vaccinated: true,
        neutered: true,
        goodWith: ["Children", "Seniors", "Other pets"],
        activityLevel: "Low to Medium"
    },
    {
        id: 9,
        name: "BUDDY",
        age: 4,
        weight: 22,
        gender: "Male",
        personality: "Friendly & Smart",
        image: "images/dog10.png",
        description: "Buddy lives up to his name! He's everyone's friend and loves to be part of the action. His intelligence makes him a quick learner, and he already knows several tricks. Buddy is house-trained and has excellent leash manners.",
        breed: "Boxer Mix",
        vaccinated: true,
        neutered: true,
        goodWith: ["Active families", "Other dogs"],
        activityLevel: "High"
    },
    {
        id: 10,
        name: "LUCY",
        age: 3,
        weight: 18,
        gender: "Female",
        personality: "Happy & Social",
        image: "images/dog9.png",
        description: "Lucy is a social butterfly who never meets a stranger. She's always happy, with a wagging tail and a smile that can brighten the darkest day. Lucy loves playdates with other dogs and would thrive in an active household.",
        breed: "Pit Bull Mix",
        vaccinated: true,
        neutered: true,
        goodWith: ["Active owners", "Experienced dog owners", "Other dogs"],
        activityLevel: "High"
    },
    {
        id: 11,
        name: "CHARLIE",
        age: 6,
        weight: 28,
        gender: "Male",
        personality: "Relaxed & Mellow",
        image: "images/dog8.png",
        description: "Charlie is the epitome of chill. This relaxed gentleman prefers lounging on the couch to high-energy activities. He's perfectly house-trained and has excellent manners both indoors and out. Charlie would be perfect for a quiet home.",
        breed: "Rottweiler Mix",
        vaccinated: true,
        neutered: true,
        goodWith: ["Quiet homes", "Seniors", "Apartment living"],
        activityLevel: "Low"
    },
    {
        id: 12,
        name: "MOLLY",
        age: 2,
        weight: 14,
        gender: "Female",
        personality: "Curious & Clever",
        image: "images/dog7.png",
        description: "Molly's clever mind is always working! She loves puzzles, learning new tricks, and figuring out how things work. Her curiosity makes life with her an adventure, and her affectionate nature ensures plenty of cuddle time too.",
        breed: "Poodle Mix",
        vaccinated: true,
        neutered: true,
        goodWith: ["Families", "First-time owners"],
        activityLevel: "Medium"
    }
];